// This file is generated by npm run build:icons

export type IconName = (typeof iconNames)[number]

const iconNames = [
	"X",
	"Terminal",
	"Settings",
	"Send",
	"Radio",
	"Network",
	"List",
	"Layers",
	"GitMerge",
	"CornerDownRight",
	"CopySlash",
	"Columns",
	"ChevronDown",
	"Check",
	"Activity",
	"Accessibility",
	"Shield",
	"Root",
	"Layout",
] as const
