// This file is generated by npm run build:icons

export type IconName =
  | "X"
  | "Terminal"
  | "Settings"
  | "Send"
  | "Radio"
  | "Network"
  | "List"
  | "Layers"
  | "GitMerge"
  | "CornerDownRight"
  | "CopySlash"
  | "Columns"
  | "ChevronDown"
  | "Check"
  | "Activity"
  | "Accessibility"
  | "Shield";

export const iconNames = [
  "X",
  "Terminal",
  "Settings",
  "Send",
  "Radio",
  "Network",
  "List",
  "Layers",
  "GitMerge",
  "CornerDownRight",
  "CopySlash",
  "Columns",
  "ChevronDown",
  "Check",
  "Activity",
  "Accessibility",
  "Shield",
] as const;
